- src/matcher_combinators/core.clj
- src/matcher_combinators/parser.clj
- test/matcher_combinators/core_test.clj
fix failing test introduced in https://github.com/nubank/matcher-combinators/pull/9
> Fix test failure that has to do with extending parser to nil

- CHANGELOG.md
- project.clj
- src/matcher_combinators/midje.clj
- test/matcher_combinators/midje_test.clj
thanks to @pitalig for pointing this issue out
> Allow for matching with midje metaconstants

- src/matcher_combinators/test.clj
follow up to https://github.com/clojure-emacs/cider-nrepl/pull/510#issuecomment-368489307
> Add namespace to clojure.test reporting for better test framework integration

- CHANGELOG.md
- project.clj
- src/matcher_combinators/core.clj
- src/matcher_combinators/midje.clj
- src/matcher_combinators/printer.clj
- src/matcher_combinators/result.clj
- test/matcher_combinators/core_test.clj
- test/matcher_combinators/matchers_test.clj
- test/matcher_combinators/midje_test.clj
Fix for https://github.com/nubank/matcher-combinators/issues/37
Also takes a crack at using `clojure.spec`, though I haven't finished wiring it all together.
TODO: more comprehensive tests
> Choose smallest diff for in-any-order when no order matches

- CHANGELOG.md
- project.clj
- src/matcher_combinators/standalone.clj
- src/matcher_combinators/test.clj
- test/matcher_combinators/standalone_test.clj
Useful for things like https://github.com/pmatiello/mockfn/pull/3
> add standalone match? construct

- CHANGELOG.md
- project.clj
- src/matcher_combinators/core.clj
- src/matcher_combinators/parser.clj
- test/matcher_combinators/matchers_test.clj
- test/matcher_combinators/parser_test.clj
adaptation of https://github.com/nubank/matcher-combinators/pull/57
> Support for byte-arrays

- src/matcher_combinators/parser.clj
- test/matcher_combinators/parser_test.clj
> Add support for short (resolves #59)

- CHANGELOG.md
- README.md
- project.clj
- src/matcher_combinators/midje.clj
- src/matcher_combinators/test.clj
- test/matcher_combinators/midje_test.clj
- test/matcher_combinators/test_test.clj
Resolves https://github.com/nubank/matcher-combinators/issues/56
> implement exception matching

- src/matcher_combinators/test.clj
Hi @phillipm, we ran into issues with CIDER and matcher-combinators. I know a fix has been suggested [here](https://github.com/clojure-emacs/cider/issues/2215#issuecomment-368269371), but that essentially involves patching/extending CIDER and every other tool that does its own test running. I was wondering if it wouldn't be possible to fix this on the matcher-combinator side so it's compatible with any clojure.test based tool. 
In case of a mismatch we emit a custom map with {:type :mismatch} in order to do
custom rendering. The problem with this approach is that other tools and
reporters (CIDER, Cursive, eftest, ...) all need to be aware of :mismatch.
Instead emit a standard {:type :fail} method, but extend
`clojure.core/print-method` to still get the pretty printing of mismatch …
> [clojure.test] Use regular :fail instead of custom :mismatch message

- CHANGELOG.md
- project.clj
- src/cljc/matcher_combinators/cljs_test.cljc
possible fix for https://github.com/nubank/matcher-combinators/issues/85
> Fix cljs.test import

- project.clj
- src/cljc/matcher_combinators/test.cljc
This should help out on editors. This is how it looks like in emacs:
> Add arglists meta to cljtest assert expressions

- CHANGELOG.md
- project.clj
- src/cljc/matcher_combinators/dispatch.cljc
- src/cljc/matcher_combinators/parser.cljc
- test/clj/matcher_combinators/midje_test.clj
- test/clj/matcher_combinators/parser_test.clj
- test/cljs/matcher_combinators/cljs_example_test.cljs
https://github.com/nubank/matcher-combinators/issues/100
note: I don't know how to do this for clojurescript
> default matcher for Object

- src/clj/matcher_combinators/clj_test.clj
- test/clj/matcher_combinators/test_test.clj
Solution for https://github.com/nubank/matcher-combinators/issues/109
> match? in an `is` returns boolean

- CHANGELOG.md
- project.clj
- src/cljc/matcher_combinators/core.cljc
- test/clj/matcher_combinators/core_test.clj
- test/cljc/matcher_combinators/test_helpers.cljc
- test/cljs/matcher_combinators/cljs_example_test.cljs
address https://github.com/nubank/matcher-combinators/issues/124
> fix issue matching `false` value in certain contexts

- .github/workflows/clojure.yml
- .github/workflows/release.yml
The tests are run on Pull requests and before releases.
> Configure CI to run tests using java-8 and java-11

- CHANGELOG.md
- project.clj
- src/cljc/matcher_combinators/matchers.cljc
- test/clj/matcher_combinators/matchers_test.clj
addresses https://github.com/nubank/matcher-combinators/issues/151
> fix match-with + absent issue

- CHANGELOG.md
- project.clj
- src/cljc/matcher_combinators/matchers.cljc
- test/cljs/matcher_combinators/cljs_example_test.cljs
addresses https://github.com/nubank/matcher-combinators/issues/154
> fix absent reference warning

- CHANGELOG.md
- project.clj
- src/cljc/matcher_combinators/printer.cljc
- test/clj/matcher_combinators/printer_test.clj
addresses https://github.com/nubank/matcher-combinators/issues/161
> add actual/expected annotation to mismatch output

- project.clj
Bump midje just to fix clj-kondo warning for missing symbols
> Bump midje

- CHANGELOG.md
- project.clj
Forgot to update the version and changelog in https://github.com/nubank/matcher-combinators/pull/169
> update version and changelog for release

- README.md
- test/clj/matcher_combinators/matchers_test.clj
https://github.com/nubank/matcher-combinators/pull/178#discussion_r1018251597
> add `via` to readme

- project.clj
Bump midje to 1.10.7.
Related to https://github.com/marick/Midje/pull/484
> Bump midje to 1.10.7

- CHANGELOG.md
- project.clj
Related to https://github.com/nubank/matcher-combinators/pull/184
> Update version in project.clj

- CHANGELOG.md
- project.clj
- Bump midje to 1.10.9
Related to https://github.com/marick/Midje/pull/486
> Bump midje to 1.10.9

- CHANGELOG.md
- src/cljc/matcher_combinators/core.cljc
- test/cljs/matcher_combinators/cljs_example_test.cljs
fix for https://github.com/nubank/matcher-combinators/issues/181 after https://github.com/nubank/matcher-combinators/pull/178 was merged
> Address cljs warning about Exception in Via matcher

- project.clj
- resources/clj-kondo.exports/nubank/matcher-combinators/config.edn
> Add clj-kondo config for unresolved symbols

- CHANGELOG.md
- src/cljc/matcher_combinators/ansi_color.cljc
addresses https://github.com/nubank/matcher-combinators/issues/195
> Allow globally configuring ANSI color emission

- .github/workflows/release.yml
- release.sh
follow up to https://github.com/nubank/matcher-combinators/pull/197
> deps.edn migration fixup: add bb dep to release ci job

- README.md
Information about matcher-combinators maintainers and where to reach them on Slack.
> Stewards section in README

- .gitignore
- CHANGELOG.md
- src/cljc/matcher_combinators/matchers.cljc
- test/clj/matcher_combinators/matchers_test.clj
addresses https://github.com/nubank/matcher-combinators/issues/212
> Fix match-with when used with non-composite matchers
