nubank/matcher-combinators

CHANGELOG.md, project.clj, src/matcher_combinators/core.clj, test/matcher_combinators/core_test.clj, test/matcher_combinators/midje_test.clj
Fix for https://github.com/nubank/matcher-combinators/issues/2
=> Fix `subset` by permuting over elements instead of matchers

CHANGELOG.md, project.clj, src/matcher_combinators/matchers.clj, src/matcher_combinators/parser.clj, test/matcher_combinators/core_test.clj, test/matcher_combinators/parser_test.clj
The use case was for checking a function that returned
the result of schema.core/explain.
Something like
```
(fact
(s/explain {:a (s/enum :foo)}) => (match {:a '(s/enum :foo)}))
```
Felt weird to write
```
(fact
(s/explain {:a (s/enum :foo)}) => (match {:a [s/enum :foo]}))
```
even though it matches in the same way.
An alternative would be to parse lists as `equals-value`, just like
primitives.
=> Parse lists as equals-seq, same as we do for vectors

src/matcher_combinators/midje.clj, test/matcher_combinators/midje_test.clj
Support using match as any other midje checker:
```clj
(fact 
(f [1 2 3]) => 1
(provided
(f (ch/match (m/equals-seq [int? int? int?]))) => 1))
```
=> Allow (match) expressions inline within midje (provided) blocks

CHANGELOG.md, project.clj, src/matcher_combinators/core.clj, src/matcher_combinators/midje.clj, test/matcher_combinators/core_test.clj
Follow up to https://github.com/nubank/matcher-combinators/pull/5#discussion_r159091226
I believe I had implemented `matcher-combinators.midje/match` as a macro because I was trying to get it to capture form information about predicate functions. This didn't pan out (seems way too hard to do) so let's make it be a normal function instead of a macro.
When I say 'capture form information about predicate functions', I mean the following:
```clojure
(fact
1 => (match (fn [x] (= x 2))))
```
would show ` (fn [x] (= x 2))` in the matcher-combinator error message, instead of just 
```
FAIL at (form-init1300508260004661418.clj:1)
Actual result did not agree with the checking function.
Actual result:
1
Checking function: (m/match (fn [x] (= x 2)))
The checker said this about the reason:
[:mismatch …
```
=> Define 'match' checker in terms of defchecker

CHANGELOG.md, project.clj, src/matcher_combinators/midje.clj, src/matcher_combinators/parser.clj, test/matcher_combinators/midje_test.clj
Matching wasn't working with `Double`s. Fix was to add it to the parser to be interpreted as `matcher-combinators.matchers/equals-value`
Also, when midje `match` checker was passed a non-matcher, it wasn't failing correctly. Now it prints the failure message correctly
=> Add Double to parser and make midje checker fail correctly

CHANGELOG.md, project.clj, src/matcher_combinators/core.clj, src/matcher_combinators/helpers.clj, test/matcher_combinators/core_test.clj, test/matcher_combinators/helpers_test.clj, test/matcher_combinators/parser_test.clj
The following would fail because the code used `clojure.core/remove` when removing tested matchers in the in-any-order matcher permutation recursion step. `remove` will take out all entries, so both `2` matchers were incorrectly removed.
```clojure
(match (in-any-order [2 2]) [2 2])
```
=> Fix in-any-order to work with identical matchers

CHANGELOG.md, project.clj
Was trying to pull `matcher-combinators` into a repository that didn't depend on `midje` and `colorize` failed to be found. This made me realized that we weren't correctly setting up the project dependencies because everything was in the `:dev` profile.
Also removed the ` [org.clojure/tools.namespace "0.2.11"] ` dependency
=> Move dependencies out of `:dev` profile and into main profile

CHANGELOG.md, src/matcher_combinators/core.clj, test/matcher_combinators/core_test.clj
Mismatched sequences would always print using parenthesis, so it was hard to tell when you were actually dealing with vectors.
Before
```
Actual result:
[[[1]]]
Checking function: (ch/match [[[even?]]])
The checker said this about the reason:
[:mismatch
((((predicate
"clojure.core$even_QMARK_@7d3bfe75"
1))))]
```
After
```
Actual result:
[[[1]]]
Checking function: (ch/match [[[even?]]])
The checker said this about the reason:
[:mismatch
[[[(predicate
"clojure.core$even_QMARK_@7d3bfe75"
1)]]]]
```
=> Preserve sequence type in mismatch output

src/matcher_combinators/core.clj, test/matcher_combinators/core_test.clj
Now that `nil` has a `match` implementation we can't use `nil` to signify missing elements in a sequence.
=> Refactor `missing` logic to not use `nil`

CHANGELOG.md, project.clj, src/matcher_combinators/core.clj, src/matcher_combinators/matchers.clj, src/matcher_combinators/model.clj, src/matcher_combinators/printer.clj, test/matcher_combinators/core_test.clj
| before | after |
| ---- | ---- |
| ![before](https://user-images.githubusercontent.com/94817/36028172-4f893228-0d9e-11e8-9641-6b9713309f2c.png) | ![after](https://user-images.githubusercontent.com/94817/36028174-51847240-0d9e-11e8-94e7-d7d995ad2af7.png) |
=> When matcher has invalid input, fail matching without throwing exception

CHANGELOG.md, README.md, project.clj, src/matcher_combinators/core.clj, src/matcher_combinators/matchers.clj, src/matcher_combinators/parser.clj, test/matcher_combinators/core_test.clj, test/matcher_combinators/midje_test.clj, test/matcher_combinators/parser_test.clj, test/matcher_combinators/test_test.clj
We currently have unique matcher names for maps, sequences, and values.
This potentially introduces overhead for the user to remember the unique names in every context (I say potentially because I'm undecided if it is better to overload names or have unique names for every specific matcher).
This PR explores the idea of renaming
- `equals-map`, `equals-seq`, and `equals-value` to `equals` 
- `contains-map` and `subset` to `embeds`
- `subseq` to `prefix-seq`
and dispatch to the correct matcher logic based on the shape of the `expected` argument
Also introduced are matchers for sets
- `equals` and `embeds` work for sets
- `set-equals` and `set-embeds` allow one to use the same submatcher more than once by accepting a sequence instead of a set as the `expected` argument. That is `(match …
=> Rename matchers and implement set matchers

CHANGELOG.md, project.clj, src/matcher_combinators/core.clj, src/matcher_combinators/matchers.clj, test/matcher_combinators/core_test.clj
I don't think `select?` is needed with the changes in https://github.com/nubank/matcher-combinators/pull/10
=> Remove select? from Matcher protocol

CHANGELOG.md, project.clj, src/matcher_combinators/parser.clj, test/matcher_combinators/midje_test.clj
Forgot to add this in https://github.com/nubank/matcher-combinators/pull/20
=> Set `equals` as default matcher for set

src/matcher_combinators/parser.clj, test/matcher_combinators/parser_test.clj
Currently when comparing numbers of these types an exception will be raised,
since they don't implement the Matcher protocol.
=> Add support for java.lang.Integer and java.lang.Float

CHANGELOG.md, project.clj, src/matcher_combinators/core.clj, src/matcher_combinators/parser.clj, test/matcher_combinators/core_test.clj, test/matcher_combinators/parser_test.clj
`set` and `in-any-order` mismatches that came up due to differing matcher/actual element counts weren't showing very fine-grained diffs. This fixes that by showing what elements or matchers were left unmatched.
Also fixes issue where predicate matchers were getting called with `:matcher-combinators.core/missing` keys. In these cases, the predicate call should be short-circuited to generate a mismatch.
=> Improve mismatch output for differing counts

CHANGELOG.md, project.clj, src/matcher_combinators/core.clj, test/matcher_combinators/core_test.clj
map related matchers that matched against missing values would return `[:mismatch (Mismatch {:whatever 'foo} :matcher-combinators.core/missing)]` instead of `[:mismatch (Missing {:whatever 'foo})]`
=> Fix issue where missing was showing as mismatch

CHANGELOG.md, project.clj, src/matcher_combinators/core.clj, test/matcher_combinators/core_test.clj, test/matcher_combinators/midje_test.clj
fix for https://github.com/nubank/matcher-combinators/issues/39
=> Fix for sequence-match reporting seqs in reverse order

CHANGELOG.md, README.md, project.clj, src/matcher_combinators/core.clj, src/matcher_combinators/matchers.clj, src/matcher_combinators/parser.clj, test/matcher_combinators/matchers_test.clj, test/matcher_combinators/midje_test.clj
In Midje checkers you can write a regex and it uses it as a checking predicate.
The same would be nice for matcher-combinators
For example:
```clojure
(fact "treat regex as predicate in match"
{:one "1"} => (match {:one #"1"}))
```
example mismatch output
```clojure
(fact "when a regex doesn't match"
{:one "1"} => (ch/match {:one #"2"}))
```
results in:
```
FAIL "treat regex as predicate in match" at (midje_test.clj:220)
Actual result did not agree with the checking function.
Actual result:
{:one "1"}
Checking function: (ch/match {:one #"2"})
The checker said this about the reason:
[:mismatch {:one (mismatch #"2" "1")}]
```
and
```clojure
(fact "trying to apply regex to wrong type"
{:one 1} => (ch/match {:one #"2"}))
```
results in:
```
Actual result did not agree with the checking …
```
=> Add regex matcher

src/matcher_combinators/midje.clj
Hey :wave: `import` doesn't load Clojure code but just loads Java classes. In order for Java classes based on Clojure code to be available those namespaces have to be loaded. 
You probably never ran into this because `midje.sweet` and other API namespaces transitively load the metaconstant namespace. 
Thanks to @hiredman for pointing me in the right direction to fix this on the Clojurians slack.
EDIT: After you publish a release with this change it should work on cljdoc. You may also want to consider deleting `doc/intro.md` before cutting the release since it doesn't have any content but will be included in the documentation via cljdoc's [article inference](https://github.com/cljdoc/cljdoc/blob/master/doc/userguide/for-library-authors.adoc#auto-inferred-articles).
=> ensure metaconstant ns is loaded before Java classes from it are loaded

CHANGELOG.md, project.clj, src/matcher_combinators/core.clj, src/matcher_combinators/helpers.clj, test/matcher_combinators/core_test.clj, test/matcher_combinators/matchers_test.clj
Fix for https://github.com/nubank/matcher-combinators/issues/47
Was caused because the permutation helper I had defined wasn't computing all permutations, only computing permutations created by rotating the sequence.
Calculating all permutations might be heavy handed, but prefer to refactor it once it proves to be a bottleneck
=> Fix for seq embeds matching due to not all permutations being computed

src/matcher_combinators/parser.clj, test/matcher_combinators/midje_test.clj
When comparing LocalTime types an exception is raised, as the matcher protocol for this class is not implemented.
=> Add support for java.time.LocalTime

project.clj, src/cljc/matcher_combinators/test.cljc
As it's not being directly used by the code that requires it, linters keep complaining of unused import when requiring `matcher-combinators.test`.
Now clients can write `[matcher-combinators.test :refer [match?]]` and stop linters from deleting this line. And, as it's not declared outside from clojure test's checks, so it still works as intended.
=> Add declare to stop linters from erasing require

src/cljc/matcher_combinators/cljs_test.cljc, src/cljc/matcher_combinators/core.cljc
Fix #73 
While this makes possible to use shadow-cljs with this library, this doesn't fix the warnings in the issue, but at least `:target :node-tests` and others run now.
I didn't test with `:target :browser-tests`, but it should run - unless you're using devcards, because with the warnings Shadow-CLJS will not reload the code on the browser.
UPDATE:
I was able to fix most of the warnings except the ones on `lex-permutations` because it is external from this library.
=> Fix refer on cljs side

project.clj
With the recently published version of combinatorics, shadow-cljs is able to compile this project without any warning.
=> Version bump of math.combinatorics

CHANGELOG.md, README.md, project.clj, src/clj/matcher_combinators/clj_test.clj, src/clj/matcher_combinators/midje.clj, src/cljc/matcher_combinators/cljs_test.cljc, src/cljc/matcher_combinators/core.cljc, src/cljc/matcher_combinators/dispatch.cljc, src/cljc/matcher_combinators/parser.cljc, src/cljc/matcher_combinators/test.cljc, src/cljc/matcher_combinators/utils.cljc, test/clj/matcher_combinators/core_test.clj, test/clj/matcher_combinators/dispatch_test.clj, test/clj/matcher_combinators/test_test.clj, test/cljs/matcher_combinators/cljs_example_test.cljs
another attempt at https://github.com/nubank/matcher-combinators/pull/29
Inside the context of `match?` (clojure.test) / `match` (midje), data-structures are assigned default matchers, which eliminates the need to wrap data-structures with matcher-combinators when your desired matching behavior matches the defaults.
But what if your desired matching behavior deviates from the defaults?
For example, if you want to do exact map matching you need to use a log of `m/equals`:
```clojure
(deftest exact-map-matching-by-hand
(is (match? (m/equals {:a (m/equals {:b (m/equals {:c odd?})})}))
{:a {:b {:c 1}}})
;; without m/equals, the system defaults to m/embeds for maps,
;; which has looser matching properties
(is (match? {:a {:b {:c odd?}}}
{:a {:b {:c 1 :extra-c 0} :extra-b 0} :extra-a 0})))
``` …
=> introduce match-with, match-equals, match-roughly

CHANGELOG.md, project.clj, src/clj/matcher_combinators/clj_test.clj
mismatches for a file like 
```
1 (ns example (:require [clojure.test :refer :all] [matcher-combinators.test :refer [match?]]))
2 (deftest example
3   (testing "foo"
4     (is (match? 1 2))))
```
would show
```
FAIL in (example) (clj_test.clj:26)
foo
expected: (match? 1 2)
actual: (mismatch 1 2)
```
instead of
```
FAIL in (example) (scratch.clj:4)
foo
expected: (match? 1 2)
actual: (mismatch 1 2)
```
=> fix clojure.test line number / file name report issue

CHANGELOG.md, project.clj, src/cljc/matcher_combinators/core.cljc, src/cljc/matcher_combinators/dispatch.cljc, src/cljc/matcher_combinators/parser.cljc, test/clj/matcher_combinators/parser_test.clj, test/cljs/matcher_combinators/cljs_example_test.cljs
In the snippet:
```clojure
(fact "bare URI"
(java.net.URI. "http://example.com") => (match (java.net.URI. "http://example.com")))
(fact "URI in map"
{:a (java.net.URI. "http://example.com")} => (match {:a (java.net.URI. "http://example.com")}))
```
Before the change:
- the "bare URI" fact would return false and say that `Input wasn't a matcher`;
- the "URI in map" fact would throw an `IllegalArgumentException` because
`java.net.URI` doesn't implement the `#'matcher-combinators.core/Matcher`
protocol.
After the change both would match and return true.
=> Implement core/Matcher for java.net.URI using mimic-matcher

CHANGELOG.md, project.clj, src/cljc/matcher_combinators/dispatch.cljc, src/cljc/matcher_combinators/parser.cljc, test/clj/matcher_combinators/dispatch_test.clj, test/clj/matcher_combinators/parser_test.clj
Never heard of `chunked-seq` in clojure but I guess they are a thing because a test was failing because it didn't have the match protocol implemented for it.
didn't find much info on them, maybe https://stackoverflow.com/questions/25711534/what-does-types-like-clojure-lang-persistentvectorchunkedseq-mean-in-clojure
=> Default matcher for chunked-seq

CHANGELOG.md, src/cljc/matcher_combinators/utils.cljc
It was code adapted from midje and I don't know why the `+'` was used instead of `+`.
addresses https://github.com/nubank/matcher-combinators/issues/90
=> replace +' with + in roughly matching

CHANGELOG.md, project.clj, src/clj/matcher_combinators/clj_test.clj, src/cljc/matcher_combinators/test.cljc, test/clj/matcher_combinators/dispatch_test.clj, test/clj/matcher_combinators/midje_test.clj, test/clj/matcher_combinators/parser_test.clj, test/clj/matcher_combinators/test_test.clj
Allow the omission of the first argument of `thrown-match?`, which is the Throwable subclass and which is almost always `ExceptionInfo`, so now the following works:
`(thrown-match? {:foo 1} (bang!)`
The 3-arity continues to work too:
`(thrown-match? ExceptionInfo {:foo 1} (bang!))`
Also, a few minor housekeeping changes:
* Ensure `lein lint` works, and run `lein lint-fix`
* Eliminate a couple unused aliases
* Add a few more test cases for `clojure.test/are`, including `with-redefs` to clarify the appropriate place to wrap (inside `match?`, not around)
=> Optionally allow omitting the first argument to `thrown-match?`

CHANGELOG.md, project.clj, src/cljc/matcher_combinators/standalone.cljc, test/clj/matcher_combinators/standalone_test.clj
This is in response to #101 
Before this PR, if you want to use matcher-combinators outside of clojure.test or midje, you have to require the `matcher-combinators.parser` namespace, e.g.
```clojure
(require '[matcher-combinators.core :refer [match]]
'[matcher-combinators.dispatch] ;; just because
)
(match 37 (count things))
```
That's fine if you happen to know about it, but it is not documented and, arguably, should not be a user-facing namespace.
With this PR you can just use the (already existing) `matcher-combinators.standalone` namespace:
```clojure
(require '[matcher-combinators.standalone :refer [match]])
(match 37 (count things))
```
=> add match fn to standalone ns

src/cljc/matcher_combinators/parser.cljc, test/clj/matcher_combinators/parser_test.clj
In the context of these macros, `(match ...` was resolving to `(matcher-combinators.parser/match ...)`, which is not a thing. It happened to work because `extend-protocol` happens to strip the namespace off of symbol, so `any-namespace-at-all/match` is the same as `match`, but we can't count on that implementation detail.
=> specify ~'match in macro

CHANGELOG.md, project.clj, src/clj/matcher_combinators/clj_test.clj, test/clj/matcher_combinators/test_test.clj
addresses https://github.com/nubank/matcher-combinators/issues/118
Double, double toil and trouble;
Fire burn and caldron bubble.
Fillet of a fenny snake,
In the caldron boil and bake;
Eye of newt and toe of frog,
Wool of bat and tongue of dog,
Adder's fork and blind-worm's sting,
Lizard's leg and howlet's wing,
For a charm of powerful trouble,
Like a hell-broth boil and bubble.
=> fix double eval in match run context

project.clj, src/cljc/matcher_combinators/standalone.cljc, test/clj/matcher_combinators/core_test.clj, test/clj/matcher_combinators/midje_test.clj, test/clj/matcher_combinators/standalone_test.clj
`clojure.spec.test` doesn't catch this issue since it only validates `:args`, but [orchestra](https://github.com/jeaye/orchestra) catches it.
=> Replace instrumentation with orchestra + add spec for partial `match?`

CHANGELOG.md, README.md, project.clj, src/clj/matcher_combinators/midje.clj, src/cljc/matcher_combinators/core.cljc, src/cljc/matcher_combinators/dispatch.cljc, src/cljc/matcher_combinators/matchers.cljc, src/cljc/matcher_combinators/parser.cljc, src/cljc/matcher_combinators/standalone.cljc, test/clj/matcher_combinators/core_test.clj, test/clj/matcher_combinators/dispatch_test.clj, test/clj/matcher_combinators/matchers_test.clj, test/clj/matcher_combinators/midje_test.clj, test/clj/matcher_combinators/parser_test.clj
Here's a proposed solution for #110 that @fernando-nubank and I cooked up.
`matcher-for` creates a matcher for you, so you can inspect it:
```clojure
(matchers/matcher-for 37)
;; => matcher_combinators.core.Value#{:expected 37}
```
And then you can also then use it!
```clojure
(let [m (matchers/matcher-for 37)]
(standalone/match? m 37))
;; => true
```
It even works within `match-with?`:
```clojure
(deftest matcher-for-works-within-match-with
(is (match-with? {java.lang.Long greater-than-matcher}
(matchers/matcher-for 4)
5)))
```
This PR also moves some tests around and converts more from midje to clojure.test (and adds a generative for `matcher-for`.
- note that it is a breaking change for custom implementations of `Matcher`
=> matcher-for

CHANGELOG.md, src/cljc/matcher_combinators/core.cljc, test/clj/matcher_combinators/standalone_test.clj
Solution for issue https://github.com/nubank/matcher-combinators/issues/116.
Clojure only recognizes `IPersistentSet` as `set?` because `java.util.Set` has no immutability semantic baked in. For the purposes of matching, we only need to read the sets, so this PR applies set matching semantics to instances of `java.util.Set` as well as `clojure.lang.IPersistentSet`.
=> Use set matcher if the expected is a clojure set or a java set

CHANGELOG.md, src/clj/matcher_combinators/clj_test.clj, src/clj/matcher_combinators/midje.clj, src/cljc/matcher_combinators/cljs_test.cljc, src/cljc/matcher_combinators/core.cljc, src/cljc/matcher_combinators/standalone.cljc, test/clj/matcher_combinators/core_test.clj, test/clj/matcher_combinators/matchers_test.clj, test/clj/matcher_combinators/midje_test.clj, test/clj/matcher_combinators/parser_test.clj, test/clj/matcher_combinators/test_helpers.clj, test/clj/matcher_combinators/test_test.clj
There are currently 3 versions of `match?`:
* `matcher-combinators.core/match?`
* `matcher-combinators.standalone/match?`
* `matcher-combinators.test/match?` (clojure.test `assert-expr` - not really a function)
`core/match?` receives a match result (map) while the others receive expected/actual values.
This PR eliminates the confusion by deprecating `core/match?` and replacing it with a new `indicates-match?` function.
This is not a breaking change, and will have almost no fan-out within Nubank.
=> Add `indicates-match?` (and deprecate `core/match?`)

CHANGELOG.md, project.clj, src/cljc/matcher_combinators/parser.cljc, src/cljc/matcher_combinators/standalone.cljc, test/cljc/matcher_combinators/test_helpers.cljc, test/cljs/matcher_combinators/cljs_example_test.cljs
This PR adds `Symbol` to the cljs types that get `Matcher` implementations.
Also, converts some cljs tests to property based tests (which was actually discovered that `Symbol` was missing).
=> add Matcher impl for Symbol in cljs

CHANGELOG.md, src/clj/matcher_combinators/clj_test.clj, src/clj/matcher_combinators/midje.clj, src/cljc/matcher_combinators/matchers.cljc, src/cljc/matcher_combinators/utils.cljc, test/clj/matcher_combinators/matchers_test.clj
This PR adds a new `within-delta` matcher, intended to replace the midje `match-roughly` checker and clojure.test `match-roughly?` assert expr
```clojure
;; before
(is (match-roughly? <delta> <expected> <actual>))
;; after
(is (match? (within-delta <delta> <expected> <actual>))
;; or (for nested values)
(is (match? (match-with [number? (within-delta <delta>)] <expected>)
<actual>))
```
=> Add within-delta matcher

CHANGELOG.md, README.md, project.clj, src/clj/matcher_combinators/clj_test.clj, src/cljc/matcher_combinators/core.cljc
This PR deprecates the `match-with?`, `match-equals?`, and `match-roughly?` assert expressions now that we can express all of those in terms of matchers.
=> deprecate some assert exprs

.github/workflows/release.yml
Clojars changed its authorization to use [Deploy Tokens](https://github.com/clojars/clojars-web/wiki/Deploy-Tokens).
This also stops using a [secret](https://github.com/nubank/matcher-combinators/settings/secrets) for Clojars username because this info is not private.
=> Use authorization token to deploy on Clojars

CHANGELOG.md, project.clj, src/cljc/matcher_combinators/utils.cljc, test/clj/matcher_combinators/test_test.clj
Allow using BigDecimal as delta for match-roughly and within-delta.
=> Keep compatibility with BigDecimal

src/cljc/matcher_combinators/utils.cljc, test/clj/matcher_combinators/matchers_test.clj
- check for decimal instead of catching Exception when asking if
decimal value is infinite or NaN
- update test to generate more types of numbers for delta
This is a minor internal refactoring that will not effect behavior, so not even mentioning it in changelog or bumping version. It'll get subsumed by the next release.
=> refactor processable-number? helper fn for within-delta

CHANGELOG.md, project.clj, src/cljc/matcher_combinators/matchers.cljc, test/clj/matcher_combinators/matchers_test.clj, test/cljc/matcher_combinators/test_helpers.cljc
This fixes a 3.0.0 bug when the expected value in `(match-with [pred delta] <expected>)` includes a list.
It also introduces an arity-1 version of `within-delta` so you don't have to wrap it in a partial to use it in `match-with`
=> fix within delta in match with bug

src/clj/matcher_combinators/midje.clj, src/cljc/matcher_combinators/test.cljc, test/clj/matcher_combinators/matchers_test.clj, test/clj/matcher_combinators/midje_test.clj, test/clj/matcher_combinators/test_test.clj, test/cljc/matcher_combinators/test_helpers.cljc
Use `abs-value-matcher` in test cases (easier to reason about than `greater-than-matcher` IMO)
=> clean up some tests

README.md
I happened to notice a misplaced paren in the README examples.
=> Fix parens in README test example

CHANGELOG.md, project.clj, src/cljc/matcher_combinators/utils.cljc
```
------ WARNING - :undeclared-var -----------------------------------------------
Resource: matcher_combinators/utils.cljc:13:8
Use of undeclared Var matcher-combinators.utils/decimal?
--------------------------------------------------------------------------------
```
=> Fix cljs warning for undeclared var decimal?

src/cljc/matcher_combinators/core.cljc, src/cljc/matcher_combinators/matchers.cljc
generally a nice little standardization of existing code but also needed to implement printing underlying matcher for the mismatch matcher: https://github.com/nubank/matcher-combinators/pull/158/files#r646551305
=> Lift matcher name logic to matcher protocol

src/cljc/matcher_combinators/core.cljc
Don't know what is going on here, but looks like there was a misspell which sent me a lot of warnings in the console.
```
------ WARNING #1 - :undeclared-var --------------------------------------------
Resource: matcher_combinators/core.cljc:491:51
Use of undeclared Var matcher-combinators.core/Exception
```
=> Fixed `printable-matcher` cljs error catch

README.md, src/cljc/matcher_combinators/matchers.cljc
I recently realized that, for maps, `equals` does not have similar behavior to the clojure standard `equals`, as it only modifies the matches being done on the top level map.
This is stated in the readme (sections [built-in matchers](https://github.com/nubank/matcher-combinators#built-in-matchers) and [overriding default matchers](https://github.com/nubank/matcher-combinators#overriding-default-matchers)).
However, nothing is stated in the docstring (which is where I assume developers would look at more often, especially given IDE integrations). I've added a note there to try and make this more obvious.
I've also added an extra note in the README to highlight this point
=> Add note to equals docstring

project.clj, src/cljc/matcher_combinators/utils.cljc
Clojure-1.11.0 introduces some new functions to clojure.core that replace custom functions in some libraries, which produces "WARNING: xxx already refers to" warnings.
This PR eliminates those warnings by upgrading a transitive dependency that avoids it and using :refer-clojure with `:exclude` for warnings emanating from this lib.
=> upgrade to clojure-1.11.0, eliminate "already refers to" warnings

CHANGELOG.md, project.clj, src/cljc/matcher_combinators/core.cljc, test/clj/matcher_combinators/core_test.clj
This fails
```clojure
(deftest person-test
,,,
(match? {:first-name "David"} (fn-that-returns-datomic-entity-including {:first-name "David"}))
```
The reason is that the `embeds` matcher checks to see that the actual value is a `map?`, which a Datomic EntityMap is not.
Generalize the type check for the actual value to allow for anything that is `associative?` but not `sequential?` (to avoid comparing vectors with maps).
=> support map-like values as actuals in embeds matcher

src/cljc/matcher_combinators/matchers.cljc
Document that in-any-order is known to be expensive for large sequences, and offer an alternative approach (sort both sequences).
=> add warning about in-any-order

.clj-kondo/config.edn, .lsp/config.edn, project.clj, src/clj/matcher_combinators/clj_test.clj, src/clj/matcher_combinators/midje.clj, test/clj/matcher_combinators/core_test.clj, test/clj/matcher_combinators/matchers_test.clj, test/clj/matcher_combinators/midje_test.clj, test/clj/matcher_combinators/parser_test.clj, test/clj/matcher_combinators/printer_test.clj, test/clj/matcher_combinators/standalone_test.clj, test/clj/matcher_combinators/test_test.clj, test/cljc/matcher_combinators/test_helpers.cljc
We're standardizing on clojure.test at NU. This PR updates some tests to clojure.test and also adds clojure-lsp to the project (hence all the reformatting). The meat of this PR is in core_test.clj
=> migrate tests from midje to clojure.test

CHANGELOG.md, project.clj, src/cljc/matcher_combinators/core.cljc, src/cljc/matcher_combinators/matchers.cljc, test/clj/matcher_combinators/matchers_test.clj
it which transforms the `actual` data-structure before applying the `expected` matcher.
For example, it allows one to match a nested string as an clojure map:
```
(is (match? {:payloads [(m/via read-string {:foo :bar})]}
{:payloads [\"{:foo :bar}\"]}))
```
(additional context in [#148](https://github.com/nubank/matcher-combinators/issues/148) and [#175](https://github.com/nubank/matcher-combinators/issues/175))
also bump midje and remove now unneeded `io.aviso/pretty` version pinning
=> `Via` matcher

README.md
Add slack chat badge for new #matcher-combinators channel on Clojurians Slack.
=> docs: add slack chat badge

CHANGELOG.md, src/cljc/matcher_combinators/matchers.cljc, test/clj/matcher_combinators/matchers_test.clj
addresses https://github.com/nubank/matcher-combinators/issues/145
This is already possible in the PredMatcher defrecord. This change extends it to the `pred` matcher that calls to PredMatcher.
```clojure
(is (match? {:payloads (m/pred pos?)}
{:payloads -1}))
; FAIL
; expected: (match? {:payloads (m/pred pos?)} {:payloads -1})
;   actual: {:payloads
;  {:expected
;   (pred
;    #object[matcher_combinators.matchers$pred 0xbb81ab9 "matcher_combinators.matchers$pred@bb81ab9"])
;   :actual -1}}
```
```clojure
(is (match? {:payloads (m/pred pos? "positive number")}
{:payloads -1}))
; FAIL
; expected: (match? {:payloads (m/pred pos? "positive number")} {:payloads -1})
;   actual: {:payloads {:expected "positive number", :actual -1}}
```
=> Allow providing a description to pred matcher

CHANGELOG.md, README.md, src/cljc/matcher_combinators/core.cljc, src/cljc/matcher_combinators/matchers.cljc, test/clj/matcher_combinators/matchers_test.clj
addresses https://github.com/nubank/matcher-combinators/issues/149
an example of the difference between the new `seq-of` matcher and @dchelimsky 's temporary workaround `(defn seq-of [matcher] (fn [coll] (and (seq coll) (every? (partial matcher-combinators.standalone/match? matcher) coll))))`
not sure if this additional expressiveness is opening a can of worms in terms of the complexity available to users. It has been asked for before though in https://github.com/nubank/matcher-combinators/issues/18 and https://github.com/nubank/matcher-combinators/issues/149 and a few times during in-person chats
=> Add `seq-of`, `all-of`, and `any-of` combinators

.gitignore, README.md, deps.edn, shadow-cljs.edn, src/cljc/matcher_combinators/cljs_test.cljc, test/cljs/matcher_combinators/cljs_example_test.cljs
Should address https://github.com/nubank/matcher-combinators/issues/156 and https://github.com/nubank/matcher-combinators/issues/83, which @zampino and I ran into today ourselves.
The idea behind the fix is to apply the changes done in https://github.com/nubank/matcher-combinators/commit/7635d040fb81ad44b3587644d75bba8961269dc7 for clj clojure.test to the cljs branch of the code.
note that I still haven't figured out how to get ansi color escape codes to print well in the browser. If anyone has ideas please chime in. (EDIT: calling `(matcher-combinators.ansi-color/disable!)
` from https://github.com/nubank/matcher-combinators/pull/196 can do it)
I'm adding a `deps.edn` file for ease of launching `shadow-cljs`. I imagine nubank will still do deploys using its `lein` based-infra (assuming a …
=> Make cljs version work with browser tests

resources/clj-kondo.exports/nubank/matcher-combinators/config.edn
The exported clj-kondo configuration currently only considers Clojure's `clojure.test`, but not ClojureScript's `cljs.test`. Therefore you'll get linter errors when using `match?` in ClojureScript tests.
=> Configure clj-kondo for ClojureScript as well

README.md, src/cljc/matcher_combinators/matchers.cljc
Matcher `seq-of` expects a non-empty sequence, but it wasn't clear from the docs.
=> Extra info for seq-of

CHANGELOG.md, bb.edn, shadow-cljs.edn, src/cljc/matcher_combinators/matchers.cljc, version.edn
follow-up to https://github.com/nubank/matcher-combinators/pull/213/ because it left some of the CLJS tests failing (I guess they don't fail CI; will need to look into that)
=> Fix more issues when using non-composite matchers (`m/regex`, `m/pred`, etc)   inside `match-with`

.gitignore, CHANGELOG.md, src/clj/matcher_combinators/clj_test.clj, src/cljc/matcher_combinators/ansi_color.cljc, src/cljc/matcher_combinators/config.cljc, src/cljc/matcher_combinators/core.cljc, src/cljc/matcher_combinators/matchers.cljc, src/cljc/matcher_combinators/printer.cljc, test/clj/matcher_combinators/config_test.clj, version.edn
addresses https://github.com/nubank/matcher-combinators/issues/159 by allowing user to manually turn on output redaction, which removes all fully-matched data-structures from the output. When output is redacted a `'...` entry is added to the top level mismatching data-structure. This helps keep the context that what you are seeing isn't the actual full form.
```clojure
(matcher-combinators.config/disable-abbreviation!)
(is (match? {:a [1 2 {:a 2 :b [4 5] :c [2 [3 4]]}]}
{:a [1 2 {:a 2 :b [4 6] :c [2 [3 4]]}]})
"this is standard output")
(matcher-combinators.config/enable-abbreviation!)
(is (match? {:a [1 2 {:a 2 :b [4 5] :c [2 [3 4]]}]}
{:a [1 2 {:a 2 :b [4 6] :c [2 [3 4]]}]})
"this is abbreviated")
```
we get:
```clojure
(matcher-combinators.config/disable-abbreviation!)
(is (match? [1 2 …
```
=> Redact fully-matched data-structures from output

CHANGELOG.md, src/cljc/matcher_combinators/printer.cljc, test/clj/matcher_combinators/printer_test.clj, version.edn
I was testing the [experimental abbreviation feature](https://github.com/nubank/matcher-combinators/pull/214) on a list of datomic entities and noticed some new exceptions.
Datomic entities are tricky to work with in the presence of `clojure.walk` functions because you can't assoc/cons onto them. Generally matcher-combinators doesn't work too well on them but because of this. 
In this particular case, I realized that it was because the walk was descending into missing/unexpected data, which shouldn't be abbreviated at all. If that data is a datomic entity, it raises an exception. So to avoid such exceptions, and data traversal, I added a patched version of prewalk that allows not descending into elements that satisfy a predicate.
=> Adapt abbreviation algorithm to not visit complete mismatch structures

CHANGELOG.md, README.md, src/cljc/matcher_combinators/matchers.cljc, test/clj/matcher_combinators/matchers_test.clj, version.edn
Create `nested-equals` function to match nested maps with `equals` and providing a documentation closer to the code about the nested behavior for matchers.
See https://github.com/nubank/matcher-combinators/issues/217
=> Create nested-equals matcher

deps.edn
Even after [adding the license](https://github.com/nubank/matcher-combinators/pull/219) to the POM file, we still [can not deploy to clojars](https://github.com/nubank/matcher-combinators/actions/runs/7820320633/job/21334888472).
After some analysis, I discovered the problem was related to the `tools.deps` version (`0.16.1264`) being used that does not support the usage of the `:pom-data`. 
So I'm bumping the `tools.build` version to generate the correct POM file. I could verify that everything was correct by executing `bb jar` and checking the file on `target/classes/META-INF/maven/nubank/matcher-combinators/pom.xml`
=> Bump clojure tools versions
